Map View Integraion & fix pagination on blog
evercam/evercam-static pull request #30
Opened 2023-06-09 07:03 UTC by studentofcoding

- Use google maps api loader & fix blog list pagination

2023-06-09 07:29 UTC, studentofcoding commented
Also fix Canonical

2023-06-12 07:50 UTC, yzdbg requested changes

2023-06-12 07:50 UTC, yzdbg commented on nuxt.config.js
> +            siteUrl: 'https://evercam.sg',
We should be able to infer this based on the `defaultLocale` now.

We should add a helper function `getDomainByLocale(locale)` in the `locale-domains` module.

2023-06-12 07:50 UTC, yzdbg commented on nuxt.config.js
> +            language: 'en-sg', // prefer more explicit language codes like `en-AU` over `en`
We should set this to `defaultLocale`

2023-06-12 07:50 UTC, yzdbg commented on storyblok/pages/projects/SectionAllProjects.vue
> +      mapStyleJson: [
This is a bit long (200 lines) I think we should move it to a dedicated file and import it.

2023-06-12 07:50 UTC, yzdbg commented on storyblok/pages/projects/SectionAllProjects.vue
> +    },
This will load maps every time the user toggles between maps and gird, we can probably get away with loading once and using a `v-show` where needed.

2023-06-12 07:50 UTC, yzdbg commented on storyblok/pages/projects/SectionAllProjects.vue
> +        google.maps.event.clearInstanceListeners(document);
Please use `async/await` syntax instead here, we recommend using `async/await` where possible, in order to minimize promise chaining

2023-06-12 07:50 UTC, yzdbg commented on storyblok/pages/projects/SectionAllProjects.vue
> +              if (!Number.isNaN(lat) && !Number.isNaN(long)) {
This can be combined into a single statement : `if (lat && long && !isNaN(lat) && !isNaN(long))`

2023-06-13 06:22 UTC, studentofcoding commented
All things are resolved now @yzdbg

2023-06-13 11:58 UTC, yzdbg requested changes

2023-06-13 11:58 UTC, yzdbg commented on storyblok/pages/projects/SectionAllProjects.vue
> +        google.maps.event.clearInstanceListeners(document);
@studentofcoding we want to relplace the `.then` with `async/await`

2023-06-13 11:58 UTC, yzdbg commented on storyblok/pages/projects/SectionAllProjects.vue
> +    },
This will still call `this.loadGoogleMap();` everytime we switch tabs, right ? We seek to avoid that if possible.

2023-06-13 11:58 UTC, yzdbg commented on nuxt.config.js
> +            siteUrl: 'https://evercam.sg',
@studentofcoding Can we get rid of that env variable ? we can infer it based on the default locale.

> We should add a helper function getDomainByLocale(locale) in the locale-domains module.

2023-06-14 03:41 UTC, studentofcoding commented on storyblok/pages/projects/SectionAllProjects.vue
> +    },
Done

2023-06-14 03:41 UTC, studentofcoding commented on storyblok/pages/projects/SectionAllProjects.vue
> +        google.maps.event.clearInstanceListeners(document);
Done

2023-06-14 15:31 UTC, yzdbg approved these changes

2023-06-14 15:31 UTC, yzdbg commented on app.vue
> -    <OgImageStatic />
Are these no longer needed ?

2023-06-14 15:31 UTC, yzdbg commented on nuxt.config.js
> +            siteUrl: process.env.NUXT_PUBLIC_SITE_URL,
This could be :
```suggestion
            siteUrl: localeDomains.getDomainByLocale(process.env.DEFAULT_LOCALE),
```

---

```javascript
// locale-domains.js

module.exports = [
  { code: 'en-gb', name: 'UK', domain: process.env.DOMAIN_UK },
  { code: 'en-sg', name: 'SG', domain: process.env.DOMAIN_SG },
  { code: 'en-ie', name: 'IE', domain: process.env.DOMAIN_IE },
  { code: 'en-au', name: 'AU', domain: process.env.DOMAIN_AU },
  { code: 'en-us', name: 'US', domain: process.env.DOMAIN_US },
  { code: 'pl', name: 'PL', domain: process.env.DOMAIN_PL }
];

function getDomainByLocale(locale) {
  const localeObj = module.exports.find(obj => obj.code === locale);
  return localeObj ? localeObj.domain : null;
}

module.exports.getDomainByLocale = getDomainByLocale;

```
After which, we can just get rid of `NUXT_PUBLIC_SITE_URL` right?

2023-06-14 15:31 UTC, yzdbg commented on storyblok/NavigationMenu.vue
> +                        <!-- phoneNumber -->
```javascript
const phoneNumber = computed(() => this.blok.phone_number || "35319194500")
const telLink = computed(() => `tel:+${this.phoneNumber}`)
```

```suggestion
                        <a :href="telLink">+{{ phoneNumber }}</a>
```

2023-06-15 03:40 UTC, studentofcoding commented on app.vue
> -    <OgImageStatic />
Yup, it's just a leftover

2023-06-15 04:15 UTC, merged